name: dj_player_app
description: Professional DJ Audio Player and Downloader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  encrypt: ^5.0.3
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  background_downloader: ^7.11.1
